name: Do test
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci 
  lint:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci 
      - name: setup lint
        run: npm init @eslint/config
  Run lint:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test